name: RELEASE

on:
  push:
    branches: [main]

jobs:
  bump-workspaces:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Cache Deno
        uses: actions/cache@v4
        with:
          path: ~/.cache/deno
          key: deno-${{ runner.os }}-${{ hashFiles('**/deno.lock', '**/deno.json') }}
          restore-keys: |
            deno-${{ runner.os }}-

      - name: Bump Workspaces
        run: deno task bump-workspaces
  release-deno:
    runs-on: ubuntu-latest
    needs: bump-workspaces
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Cache Deno
        uses: actions/cache@v4
        with:
          path: ~/.cache/deno
          key: deno-${{ runner.os }}-${{ hashFiles('**/deno.lock', '**/deno.json') }}
          restore-keys: |
            deno-${{ runner.os }}-

      - name: Release Deno
        run: deno task release
      - name: Git Push Tags
        run: git push --follow-tags origin main
